### ISSUE TITLE
[ image ] To fat

### ISSUE THREAD

**Issue by neilkuan** [BingHongLi/cloud_native_develope_environment#1]
This image is so fat.
https://github.com/BingHongLi/cloud_native_develope_environment/blob/4ed05cf37d9de5ff1d1cf27f897a2beabb4db605/dockerfile#L1

recomand use `python:3.8.5-slim`. 😁 😁 😁

**Comment by BingHongLi** [comment]
Thank! I will run all feature on python:3.8.5-slim for testing.
